name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  test_vite:
    runs-on: ubuntu-latest 
    steps:
      - name: uses nodejs latest
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
      - name: pull changes
        uses: actions/checkout@v3
      - name: run npm install
        run: npm i
      - name: run npm test
        run: npm test
